name: expressions and workflow commands
on: push
jobs:
  generate-a-secret-output:
    runs-on: ubuntu-latest
    steps:
      - name: Set the name
        id: step_one
        run: |
          echo "action_state = yellow" >> "$GITHUB_ENV"
      - run: |
          echo "${{ env.action_state }}"