on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix: 
        os: [macos-latest, ubuntu-latest]
        node_version: [12, 13, 14]

      name: My first job
      runs-on: ${{ matrix.os }}
      steps: 
        - uses: actions/setup-node@v3.6.0
          with: 
            node-version: ${{ matrix.node_version }} 
